futil.dofile("collections", "bitarray")
futil.dofile("collections", "default_table")
futil.dofile("collections", "deque")
futil.dofile("collections", "pairing_heap")
futil.dofile("collections", "point_search_tree")
futil.dofile("collections", "set")
